name: Postman CI
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  postman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Postman Collection
        uses: postmanlabs/postman-cli-action@v1
        with:
          api-key: ${{ secrets.POSTMAN_API_KEY }}
          command: collection run 52274286-2b7a442e-3e93-45ca-8ced-3ad879dbdacc -e 52274286-6b3ada60-58ed-48cb-9e47-85009c695e6c --report-events --verbose
