name: Postman CI
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  postman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Postman Collection
        uses: postmanlabs/postman-cli-action@v1
        with:
          api-key: ${{ secrets.POSTMAN_API_KEY }}
          command: collection run 52238111-dc3285c5-a9ce-4400-9efa-9dcf780be35f -e 52238111-0148799a-36f8-4048-9c43-6931fbaf5b45 --report-events --verbose
